[2025-08-20T17:03:58.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-20T17:03:58.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_avg_temp.fetch_avg manual__2025-08-20T17:03:58.214629+00:00 map_index=2 [queued]>
[2025-08-20T17:03:58.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_avg_temp.fetch_avg manual__2025-08-20T17:03:58.214629+00:00 map_index=2 [queued]>
[2025-08-20T17:03:58.878+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-08-20T17:03:58.886+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): fetch_avg> on 2025-08-20 17:03:58.214629+00:00
[2025-08-20T17:03:58.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_avg_temp', 'fetch_avg', 'manual__2025-08-20T17:03:58.214629+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/weather_avg_temp_dag.py', '--cfg-path', '/tmp/tmp2ps1vkbv', '--map-index', '2']
[2025-08-20T17:03:58.896+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask fetch_avg
[2025-08-20T17:03:58.897+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-20T17:03:58.897+0000] {standard_task_runner.py:63} INFO - Started process 202 to run task
[2025-08-20T17:03:58.929+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_avg_temp.fetch_avg manual__2025-08-20T17:03:58.214629+00:00 map_index=2 [running]> on host fbf18af1ad57
[2025-08-20T17:03:58.992+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='weather_avg_temp' AIRFLOW_CTX_TASK_ID='fetch_avg' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T17:03:58.214629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T17:03:58.214629+00:00'
[2025-08-20T17:03:58.992+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-20T17:03:59.456+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-20T17:03:59.456+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_avg_temp_dag.py", line 43, in fetch_avg
    payload = client.get_city_forecast(query, days=days)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/weatheravg/client.py", line 93, in get_city_forecast
    raise WeatherAPIError(f"HTTP {resp.status_code} for {city_query!r} (days={days}). Body: {snippet}")
weatheravg.client.WeatherAPIError: HTTP 400 for 'Boise, ID' (days=6). Body: {"error":{"code":1006,"message":"No matching location found."}}
[2025-08-20T17:03:59.464+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_avg_temp, task_id=fetch_avg, run_id=manual__2025-08-20T17:03:58.214629+00:00, map_index=2, execution_date=20250820T170358, start_date=20250820T170358, end_date=20250820T170359
[2025-08-20T17:03:59.479+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task fetch_avg (HTTP 400 for 'Boise, ID' (days=6). Body: {"error":{"code":1006,"message":"No matching location found."}}; 202)
[2025-08-20T17:03:59.511+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-20T17:03:59.519+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
